# Licensed under the MIT License.
# For details on the licensing terms, see the LICENSE file.
# SPDX-License-Identifier: MIT

# Copyright 2023-2024 (c) Fraunhofer IOSB (Author: Florian Düwel)

name: Measure code coverage

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  code-coverage:
      name: Code Coverage
      runs-on: ubuntu-22.04
      steps:

        - uses: actions/checkout@v4
        -     name: Set up QEMU
              uses: docker/setup-qemu-action@v3
        -     name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

        - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

        - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
          with:
            python-version: '3.10.14'

        - name: Install dependencies
          run: |
            sudo apt -qq update
            pip3 install -r requirements.txt

        - name: Run Coverage.py
          run: |
            coverage run --omit=tests/*,__init__.py tests/unit_tests/run_unit_tests.py
            coverage report
            coverage json
            coverage html